# Generated by Django 4.2.19 on 2025-02-21 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="description",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
