# Generated by Django 4.2.19 on 2025-02-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_myuser_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="description",
        ),
        migrations.AddField(
            model_name="myuser",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "Муж"), ("female", "Жен")],
                max_length=6,
                null=True,
            ),
        ),
    ]
